# Generated by Django 4.0.2 on 2022-02-20 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_remove_order_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='first_name',
            field=models.CharField(default='<django.db.models.query_utils.DeferredAttribute object at 0x000001DA6FAF2B20>', max_length=100),
        ),
    ]
